apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: admin
  roleRef:
    name: admin
  subjects:
  - kind: User
    name: admin
  userNames:
  - admin
- apiVersion: rbac.authorization.k8s.io/v1
  groupNames: null
  kind: RoleBinding
  metadata:
    annotations:
      openshift.io/description: Allows deploymentconfigs in this namespace to rollout
        pods in this namespace.  It is auto-managed by a controller; remove subjects
        to disable.
    creationTimestamp: null
    name: system:deployers
  roleRef:
    name: system:deployer
  subjects:
  - kind: ServiceAccount
    name: deployer
    namespace: clou0-svil
  userNames:
  - system:serviceaccount:clou0-svil:deployer
- apiVersion: rbac.authorization.k8s.io/v1
  groupNames: null
  kind: RoleBinding
  metadata:
    annotations:
      openshift.io/description: Allows builds in this namespace to push images to
        this namespace.  It is auto-managed by a controller; remove subjects to disable.
    creationTimestamp: null
    name: system:image-builders
  roleRef:
    name: system:image-builder
  subjects:
  - kind: ServiceAccount
    name: builder
    namespace: clou0-svil
  userNames:
  - system:serviceaccount:clou0-svil:builder
- apiVersion: rbac.authorization.k8s.io/v1
  groupNames:
  - system:serviceaccounts:clou0-svil
  kind: RoleBinding
  metadata:
    annotations:
      openshift.io/description: Allows all pods in this namespace to pull images from
        this namespace.  It is auto-managed by a controller; remove subjects to disable.
    creationTimestamp: null
    name: system:image-pullers
  roleRef:
    name: system:image-puller
  subjects:
  - kind: SystemGroup
    name: system:serviceaccounts:clou0-svil
  userNames: null
kind: List
metadata: {}
