apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: null
  generation: 1
  labels:
    app: prova
  name: prova
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: 172.30.1.1:5000/clou0-svil/prova
  tags:
  - items:
    - created: 2019-03-14T14:01:18Z
      dockerImageReference: 172.30.1.1:5000/clou0-svil/prova@sha256:15530cfcd233304fc3dca72349b421520fb95186e7f47fc81089c8558e86062d
      generation: 1
      image: sha256:15530cfcd233304fc3dca72349b421520fb95186e7f47fc81089c8558e86062d
    tag: latest
