apiVersion: v1
items:
- apiVersion: v1
  data:
    datasources.env: |
      DATASOURCES=FVCA0DATA,FVCA0DATAXA,FVCA0LINKS,FVCA0LINKSXA,FVCA0BACKDATA,FVCA0BACKDATAXA,MULTIDATA

      FVCA0DATA_JNDI=java:/fvca0Data
      FVCA0DATA_URL=jdbc:oracle:thin:@//ex91-scan.sede.corp.sanpaoloimi.com:1521/SFVCA0
      FVCA0DATA_MIN_POOL_SIZE=5
      FVCA0DATA_MAX_POOL_SIZE=30
      FVCA0DATA_JTA=true
      FVCA0DATA_NONXA=true
      FVCA0DATA_USERNAME=${FVCA0DATA_USERNAME_SECRET}
      FVCA0DATA_PASSWORD=${FVCA0DATA_PASSWORD_SECRET}
      FVCA0DATA_DRIVER=oracle
      FVCA0DATA_CONNECTION_CHECKER=org.jboss.jca.adapters.jdbc.extensions.oracle.OracleValidConnectionChecker
      FVCA0DATA_EXCEPTION_SORTER=org.jboss.jca.adapters.jdbc.extensions.oracle.OracleExceptionSorter
      FVCA0DATA_NEW_CONNECTION_SQL=fvcp0-svil-kelandingpage
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    labels:
      app: prova
      app-type: jboss
      cm-type: datasources
      template: eap70-isp-binary
      template-version: 1.0.9
      xpaas: 1.3.2
    name: datasources-prova-v1
kind: List
metadata: {}
