apiVersion: v1
items:
- apiVersion: v1
  data:
    logback.xml: <?xml version="1.0" encoding="UTF-8"?><configuration><appender name="STDOUT"
      class="ch.qos.logback.core.ConsoleAppender"><layout class="ch.qos.logback.classic.PatternLayout"><Pattern>%d{yyyy-MM-dd
      HH:mm:ss.SSSZ} %level [%logger] \(%thread\) %msg%n</Pattern></layout></appender><root
      level="info"><appender-ref ref="STDOUT" /></root></configuration>
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    labels:
      app: prova
      app-type: jboss
      cm-type: logging
      template: springboot-isp-binary
      template-version: 1.0.9
    name: logback-prova-v1
kind: List
metadata: {}
